### ISSUE TITLE
User ID generate issue

### ISSUE THREAD

**Issue by ShashithAdithyaWijerathne** [ShashithAdithyaWijerathne/smart-admin-backend#3]
@Naduladisanayaka494 , Upon creating the user, the UserId was successfully generated; however, it should adhere to a specific sequence. Kindly review and rectify this matter accordingly.
![image](https://github.com/ShashithAdithyaWijerathne/smart-admin-backend/assets/48553417/3198b29c-ed07-4e65-bbf0-b5ee7e688d91)

**Comment by Naduladisanayaka494** [comment]
issue fixed

**Comment by ShashithAdithyaWijerathne** [comment]
Noted
